#!/usr/bin/env bash
# Summary: Explain how the current Tcl version is set
set -e
[ -n "$TCLENV_DEBUG" ] && set -x

if [ -n "$TCLENV_VERSION" ]; then
  echo "TCLENV_VERSION environment variable"
else
  tclenv-version-file
fi
