#!/usr/bin/env bash
# Summary: List hook scripts for a given tclenv command
# Usage: tclenv hooks <command>

set -e
[ -n "$TCLENV_DEBUG" ] && set -x

# Provide tclenv completions
if [ "$1" = "--complete" ]; then
  echo exec
  echo rehash
  echo which
  exit
fi

TCLENV_COMMAND="$1"
if [ -z "$TCLENV_COMMAND" ]; then
  tclenv-help --usage hooks >&2
  exit 1
fi

if ! enable -f "${BASH_SOURCE%/*}"/tclenv-realpath.dylib realpath 2>/dev/null; then
  if [ -n "$TCLENV_NATIVE_EXT" ]; then
    echo "tclenv: failed to load \`realpath' builtin" >&2
    exit 1
  fi
READLINK=$(type -p greadlink readlink | head -1)
if [ -z "$READLINK" ]; then
  echo "tclenv: cannot find readlink - are you missing GNU coreutils?" >&2
  exit 1
fi

resolve_link() {
  $READLINK "$1"
}

realpath() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  echo "$(pwd)/$name"
  cd "$cwd"
}
fi

IFS=: hook_paths=($TCLENV_HOOK_PATH)

shopt -s nullglob
for path in "${hook_paths[@]}"; do
  for script in "$path/$TCLENV_COMMAND"/*.bash; do
    realpath "$script"
  done
done
shopt -u nullglob
