#!/usr/bin/env bash
#
# Summary: Run an executable with the selected Tcl version
#
# Usage: tclenv exec <command> [arg1 arg2...]
#
# Runs an executable by first preparing PATH so that the selected Tcl
# version's `bin' directory is at the front.
#
# For example, if the currently selected Tcl version is 1.9.3-p327:
#   tclenv exec bundle install
#
# is equivalent to:
#   PATH="$TCLENV_ROOT/versions/1.9.3-p327/bin:$PATH" bundle install

set -e
[ -n "$TCLENV_DEBUG" ] && set -x

# Provide tclenv completions
if [ "$1" = "--complete" ]; then
  exec tclenv-shims --short
fi

TCLENV_VERSION="$(tclenv-version-name)"
TCLENV_COMMAND="$1"

if [ -z "$TCLENV_COMMAND" ]; then
  tclenv-help --usage exec >&2
  exit 1
fi

export TCLENV_VERSION
TCLENV_COMMAND_PATH="$(tclenv-which "$TCLENV_COMMAND")"
TCLENV_BIN_PATH="${TCLENV_COMMAND_PATH%/*}"

OLDIFS="$IFS"
IFS=$'\n' scripts=(`tclenv-hooks exec`)
IFS="$OLDIFS"
for script in "${scripts[@]}"; do
  source "$script"
done

shift 1
if [ "$TCLENV_VERSION" != "system" ]; then
  export PATH="${TCLENV_BIN_PATH}:${PATH}"
fi
exec -a "$TCLENV_COMMAND" "$TCLENV_COMMAND_PATH" "$@"
