#!/usr/bin/env bash
# Summary: Show the current Tcl version and its origin
#
# Shows the currently selected Tcl version and how it was
# selected. To obtain only the version string, use `tclenv
# version-name'.

set -e
[ -n "$TCLENV_DEBUG" ] && set -x

echo "$(tclenv-version-name) (set by $(tclenv-version-origin))"
